name: Deploy to Amazon ECS

on:
  push:
    branches: [ main ]

concurrency:
  group: ecs-${{ github.ref }}
  cancel-in-progress: true

env:
  # Default region (UBAH jika perlu). Bisa dioverride oleh GitHub Variables/Secrets bernama AWS_REGION.
  AWS_REGION: ap-southeast-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Tentukan REGION yang dipakai: prioritas Secrets > Variables > env default
      - name: Resolve region
        id: region
        run: |
          REGION="${{ secrets.AWS_REGION || vars.AWS_REGION || env.AWS_REGION }}"
          if [ -z "$REGION" ]; then
            echo "Region tidak terdefinisi. Set env.AWS_REGION atau buat Variables/Secrets AWS_REGION."
            exit 1
          fi
          echo "value=$REGION" >> $GITHUB_OUTPUT

      - name: Show effective region
        run: echo "Using AWS region: ${{ steps.region.outputs.value }}"

      # Kredensial AWS via Access Key (bisa diganti OIDC nanti)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ steps.region.outputs.value }}

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image
        id: build
        env:
          REPO: ${{ secrets.ECR_REPOSITORY }}       # contoh: my-icons
          REGISTRY: ${{ steps.ecr.outputs.registry }} # contoh: 123456789012.dkr.ecr.ap-southeast-1.amazonaws.com
        run: |
          set -e
          IMAGE_TAG=${GITHUB_SHA}
          docker build -t "$REPO:$IMAGE_TAG" .
          docker tag "$REPO:$IMAGE_TAG" "$REGISTRY/$REPO:$IMAGE_TAG"
          docker push "$REGISTRY/$REPO:$IMAGE_TAG"
          echo "IMAGE=$REGISTRY/$REPO:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # Jika task def kamu berupa ARN di Secrets → biarkan seperti ini.
      # Jika berupa file JSON di repo (mis. ecs-task.json) → ganti secrets.ECS_TASK_DEFINITION dengan path file itu.
      - name: Render task definition
        id: render
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ secrets.ECS_TASK_DEFINITION }}
          container-name: ${{ secrets.CONTAINER_NAME }}
          image: ${{ steps.build.outputs.IMAGE }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render.outputs.task-definition }}
          service: ${{ secrets.ECS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          wait-for-service-stability: true
